id: I388B1336
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T21:29:40+00:00'
last_modified: '2022-06-09T06:16:10.254172+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ1143
  title: ལམ་འབྲས་གདམས་ངག་ཟབ་མོ་བྱུང་ཚུལ་གྱི་ཡི་གེ་དོན་གཉེར་དགའ་བ་བསྐྱེད་བྱེད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    347C:
      image_group_id: I1CZ1546
      title: Volume 1 of lam 'bras gdams ngag zab mo byung tshul gyi yi ge don gnyer
        dga' ba bskyed byed
      total_pages: 36
      order: 1
      base_file: 347C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
