id: P007127
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ1143
  title: ལམ་འབྲས་གདམས་ངག་ཟབ་མོ་བྱུང་ཚུལ་གྱི་ཡི་གེ་དོན་གཉེར་དགའ་བ་བསྐྱེད་བྱེད
  author: ''
  volumes:
    dc5f6941bda24759b4dc32fda0127912:
      image_group_id: I1CZ1546
      title: ''
      volume_number: 1
      total_pages: 36
ebook_metadata:
  title: ལམ་འབྲས་གདམས་ངག་ཟབ་མོ་བྱུང་ཚུལ་གྱི་ཡི་གེ་དོན་གཉེར་དགའ་བ་བསྐྱེད་བྱེད
  author: ''
  sku: P007127
  cover: cover.jpg
  layers:
  - pagination
