id: opecha:P007127
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ1143
  title: ལམ་འབྲས་གདམས་ངག་ཟབ་མོ་བྱུང་ཚུལ་གྱི་ཡི་གེ་དོན་གཉེར་དགའ་བ་བསྐྱེད་བྱེད
  volume:
    49b979674e494b32b9ace16828f4612b:
      image_group_id: I1CZ1546
      title: Volume 1 of lam 'bras gdams ngag zab mo byung tshul gyi yi ge don gnyer
        dga' ba bskyed byed
      volume_number: 1
      total_pages: 36
  author: ''
ebook_metadata:
  title: ལམ་འབྲས་གདམས་ངག་ཟབ་མོ་བྱུང་ཚུལ་གྱི་ཡི་གེ་དོན་གཉེར་དགའ་བ་བསྐྱེད་བྱེད
  author: ''
  sku: P007127
  cover: cover.jpg
  layers:
  - pagination
